apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/der-ambi/spring-book-dispatcher-service/k8s?ref=8845605ca0944c40459bbbcf871df44ed71ef3ea

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: dispatcher-config

images:
- name: dispatcher-service
  newName: ghcr.io/der-ambi/spring-book-dispatcher-service
  newTag: 8845605ca0944c40459bbbcf871df44ed71ef3ea

replicas:
- count: 1
  name: dispatcher-service
