apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/der-ambi/spring-book-edge-service/k8s?ref=master

patches:
  - path: patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: edge-config

images:
  - name: edge-service
    newName: ghcr.io/der-ambi/edge-service
    newTag: latest

replicas:
  - name: edge-service
    count: 1
