fullnameOverride: polar-keycloak
commonAnnotations:
  app: polar-keycloak
image:
  tag: 24.0.5
global:
  defaultStorageClass: gp2
extraEnvVars:
  - name: KEYCLOAK_EXTRA_ARGS
    value: "--import-realm"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HOSTNAME_STRICT_HTTPS
    value: "false"
  - name: KC_HOSTNAME_STRICT
    value: "false"
extraVolumeMounts:
  - name: config-volume
    mountPath: "/opt/bitnami/keycloak/data/import"
    readOnly: true
extraVolumes:
  - name: config-volume
    configMap:
      name: keycloak-config
startupProbe:
  enabled: true
resources:
  requests:
    cpu: 0.2
    memory: 756Mi
  limits:
    cpu: 2
    memory: 756Mi
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:038462785176:certificate/46b4430a-dd77-43bb-8d73-25cf678dd60e
  ingressClassName: alb
  hostname: polarkeycloak.christian-ambach.de
tls:
  enabled: true
  autoGenerated: true
logging:
  level: "DEBUG"
#ingress:
#  enabled: true
#  annotations:
#    alb.ingress.kubernetes.io/scheme: "internet-facing"

