server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: catalog_logs
    static_configs:
      - labels:
          __path__: '/tmp/catalog-service.json'
          service: catalog-service
